############################
## CHANGE THESE
############################

baseURL: 'https://xlindo.com'
title: 'xlindo'

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr


############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


